### Tensor 的类型
![image-20230905172235197](https://cdn.jsdelivr.net/gh/Hyeonwuu/Image/image-20230905172235197.png)

```python
torch.rand(size)
torch.randn(size)
torch.normal(mean, std, size)
torch.randint(low, high, size)
```


# Tensor转换

In [4]:
import torch
import numpy as np
a = torch.tensor(1)
b = a.item()
b

1

In [9]:
# list转换为tensor
a = [1,2,3]
b = torch.tensor(a)
c = b.numpy().tolist()
print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'torch.Tensor'>
<class 'list'>


# Tensor常用操作

## 获取形状

In [10]:
a = torch.zeros(2,3,5)
a.shape

torch.Size([2, 3, 5])

In [11]:
a.size()

torch.Size([2, 3, 5])

In [12]:
# 统计元素个数
a.numel()

30

## 矩阵转置
```python
permute() 和 transpose()
```

In [15]:
x = torch.rand(2,3,5)
print(x.shape)
print(x)

torch.Size([2, 3, 5])
tensor([[[0.9242, 0.2902, 0.3167, 0.1795, 0.5726],
         [0.5672, 0.8111, 0.5351, 0.4660, 0.5162],
         [0.9744, 0.0912, 0.2531, 0.6913, 0.5137]],

        [[0.9609, 0.1223, 0.2458, 0.9798, 0.1013],
         [0.1351, 0.0287, 0.7498, 0.7260, 0.1875],
         [0.1135, 0.3809, 0.3699, 0.2856, 0.7173]]])


In [16]:
x = x.permute(2,1,0)
print(x.shape)
print(x)

torch.Size([5, 3, 2])
tensor([[[0.9242, 0.9609],
         [0.5672, 0.1351],
         [0.9744, 0.1135]],

        [[0.2902, 0.1223],
         [0.8111, 0.0287],
         [0.0912, 0.3809]],

        [[0.3167, 0.2458],
         [0.5351, 0.7498],
         [0.2531, 0.3699]],

        [[0.1795, 0.9798],
         [0.4660, 0.7260],
         [0.6913, 0.2856]],

        [[0.5726, 0.1013],
         [0.5162, 0.1875],
         [0.5137, 0.7173]]])


In [17]:
x = x.transpose(1,0)
print(x.shape)

torch.Size([3, 5, 2])


## 形状变换

In [30]:
x = torch.randn(4,4)
print(x)
print(x.shape)
x = x.view(2,8)
print(x.shape)

tensor([[-0.3152,  0.0969,  0.1901,  0.2101],
        [-0.3799,  0.4912,  0.0940,  1.5157],
        [-0.9359, -0.2826,  1.6203,  0.9830],
        [-0.4975, -0.1593, -1.0720, -0.2351]])
torch.Size([4, 4])
torch.Size([2, 8])


In [33]:
x = x.permute(1,0)
x.shape

torch.Size([2, 8])

In [32]:
x.view(4,4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### view()不能处理内存不连续的tensor

## 增加维度

In [43]:
x = torch.rand(2,1,3)
x.shape

torch.Size([2, 1, 3])

In [45]:
y = x.squeeze(1)
y.shape

torch.Size([2, 3])

In [46]:
x = torch.rand(2,1,3)
y = x.unsqueeze(2)
y.shape

torch.Size([2, 1, 1, 3])