# 05 | Tensor变形记：快速掌握Tensor切分、变形等方法

## cat操作

![image-20230905191605543](https://cdn.jsdelivr.net/gh/Hyeonwuu/Image/image-20230905191605543.png)

In [2]:
import torch

A = torch.ones(3,3)
B = 2*torch.ones(3,3)
print(A)
print(B)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [3]:
C = torch.cat((A,B),0)
print(C)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [4]:
D = torch.cat((A,B),1)
print(D)

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


### 增加新的维度连接

In [5]:
A = torch.arange(0,4)
A

tensor([0, 1, 2, 3])

In [15]:
B = torch.arange(5,9)
B

tensor([5, 6, 7, 8])

In [13]:
C = torch.stack((A,B),0)
C

torch.Size([2, 4])

In [12]:
D = torch.stack((A,B),1)
D

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])

### Tensor的切分操作

In [16]:
A = torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A,2,0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [18]:
B = torch.chunk(A,3,0)
B

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))

In [19]:
A = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])
B = torch.chunk(A,4,0)
B

(tensor([1, 2, 3, 4, 5]),
 tensor([ 6,  7,  8,  9, 10]),
 tensor([11, 12, 13, 14, 15]),
 tensor([16, 17]))

In [20]:
A = torch.ones(4,4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
B = torch.chunk(A,2,0)
B

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [24]:
A = torch.rand(4,4)
A

tensor([[0.8562, 0.9650, 0.2739, 0.3332],
        [0.7022, 0.4512, 0.0334, 0.7212],
        [0.7094, 0.8709, 0.7553, 0.2990],
        [0.4037, 0.4617, 0.0634, 0.9566]])

In [25]:
B = torch.split(A,2,0)
B

(tensor([[0.8562, 0.9650, 0.2739, 0.3332],
         [0.7022, 0.4512, 0.0334, 0.7212]]),
 tensor([[0.7094, 0.8709, 0.7553, 0.2990],
         [0.4037, 0.4617, 0.0634, 0.9566]]))

In [27]:
C = torch.split(A,3,0)
C

(tensor([[0.8562, 0.9650, 0.2739, 0.3332],
         [0.7022, 0.4512, 0.0334, 0.7212],
         [0.7094, 0.8709, 0.7553, 0.2990]]),
 tensor([[0.4037, 0.4617, 0.0634, 0.9566]]))

In [28]:
A = torch.rand(5,4)
A

tensor([[0.3382, 0.8479, 0.3765, 0.4090],
        [0.8136, 0.6187, 0.2132, 0.8314],
        [0.3733, 0.3669, 0.8634, 0.6380],
        [0.7832, 0.7307, 0.3306, 0.0568],
        [0.2011, 0.9205, 0.6274, 0.9683]])

In [32]:
B = torch.split(A,(2,3),0)
B

(tensor([[0.3382, 0.8479, 0.3765, 0.4090],
         [0.8136, 0.6187, 0.2132, 0.8314]]),
 tensor([[0.3733, 0.3669, 0.8634, 0.6380],
         [0.7832, 0.7307, 0.3306, 0.0568],
         [0.2011, 0.9205, 0.6274, 0.9683]]))

### unbind 是一种降维切分的方式

In [33]:
A = torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [35]:
b = torch.unbind(A,0)
b

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

### Tensor 的索引操作

In [36]:
A = torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [37]:
B = torch.index_select(A,0,torch.tensor([1,3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [38]:
C = torch.index_select(A,1,torch.tensor([0,3]))
C

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

In [39]:
A = torch.rand(5)
A

tensor([0.0949, 0.5255, 0.9441, 0.2842, 0.2213])

In [41]:
B = A>0.3
B

tensor([False,  True,  True, False, False])

In [42]:
C = torch.masked_select(A,B)
C

tensor([0.5255, 0.9441])

In [44]:
C = torch.masked_select(A,A>0.3)
C

tensor([0.5255, 0.9441])

![image-20230905195515451](https://cdn.jsdelivr.net/gh/Hyeonwuu/Image/image-20230905195515451.png)

### 练习

In [47]:
A = torch.tensor([[4,5,7], [3,9,8],[2,3,4]])
B = torch.tensor([[1,0,0],[1,1,0],[0,0,1]])
C = torch.masked_select(A,B>0)
C

tensor([4, 3, 9, 4])