In [1]:
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self,data_tensor,target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor

    def __len__(self):
        return self.data_tensor.size(0)

    def __getitem__(self, index):
        return self.data_tensor[index],self.target_tensor[index]

In [2]:
# 生成数据
data_tensor = torch.randn(10,3)
target_tensor = torch.randint(2,(10,))

# 将数据封装成Dataset
my_dataset = MyDataset(data_tensor,target_tensor)

# 查看数据集大小
print('Dataset size:',len(my_dataset))

# 使用索引调用数据
print('tensor_data[0]:',my_dataset[0])

Dataset size: 10


# DataLoader

In [3]:
from torch.utils.data import DataLoader
tensor_dataloader = DataLoader(dataset=my_dataset,
                               batch_size=2,
                               shuffle=True,
                               num_workers=0)
# 以循环输出
for data,target in tensor_dataloader:
    print(data,target)


tensor([[ 2.3815, -1.5392, -0.5491],
        [-0.6303, -0.6102, -0.5180]]) tensor([0, 0])
tensor([[ 2.7391, -0.1984, -0.3862],
        [ 1.7561,  0.0643,  0.0418]]) tensor([1, 1])
tensor([[ 1.2019,  0.2928, -0.1562],
        [-0.3590, -0.8548, -0.1576]]) tensor([1, 0])
tensor([[ 1.4753,  0.4828,  1.2911],
        [-0.1542, -1.1074,  0.7603]]) tensor([0, 0])
tensor([[ 1.8498, -0.1495, -0.4267],
        [ 1.3611,  0.7311, -0.2269]]) tensor([0, 0])


In [7]:
# 输出一个batch
print('One batch tensor data:',iter(tensor_dataloader).__next__())

One batch tensor data: [tensor([[ 1.2019,  0.2928, -0.1562],
        [ 2.3815, -1.5392, -0.5491]]), tensor([1, 0])]


In [8]:
import torchvision
mnist_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=True,
                                           transform=None,
                                           target_transform=None,
                                           download=True)

100%|██████████| 9912422/9912422 [00:24<00:00, 410876.52it/s] 


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 517229.62it/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



100%|██████████| 1648877/1648877 [00:04<00:00, 346759.55it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 10342306.61it/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [9]:
mnist_dataset_list = list(mnist_dataset)
print(mnist_dataset_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [14]:
display(mnist_dataset_list[0][0])
print('Image label is:',mnist_dataset_list[0][1])

Image label is: 5
