In [20]:
import torch
import torch.nn as nn

input_feat = torch.tensor([[4, 1, 7, 5], [4, 4, 2, 5], [7, 7, 2, 4], [1, 0, 2, 4]])
print(input_feat)
print(input_feat.shape)

tensor([[4, 1, 7, 5],
        [4, 4, 2, 5],
        [7, 7, 2, 4],
        [1, 0, 2, 4]])
torch.Size([4, 4])


In [21]:
conv2d = nn.Conv2d(1,1,(2,2),stride=1,padding='same',bias=True)
# 默认情况随机初始化参数
print(conv2d.weight)
print(conv2d.bias)


Parameter containing:
tensor([[[[-0.2818,  0.2666],
          [ 0.0976,  0.0844]]]], requires_grad=True)
Parameter containing:
tensor([-0.0856], requires_grad=True)


In [22]:
conv2d = nn.Conv2d(1,1,(2,2),stride=1,padding='same',bias=False)
# 卷积核四个维度
kernels = torch.tensor([[[[1, 0], [2, 1]]]], dtype=torch.float32)
conv2d.weight = nn.Parameter(kernels,requires_grad=False)
print(conv2d.weight)
print(conv2d.bias)
output = conv2d(input_feat)

Parameter containing:
tensor([[[[1., 0.],
          [2., 1.]]]])
None


RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [4, 4]

In [23]:
input_feat = torch.FloatTensor([[4, 1, 7, 5], [4, 4, 2, 5], [7, 7, 2, 4], [1, 0, 2, 4]]).unsqueeze(0).unsqueeze(0)
print(input_feat)
print(input_feat.shape)

tensor([[[[4., 1., 7., 5.],
          [4., 4., 2., 5.],
          [7., 7., 2., 4.],
          [1., 0., 2., 4.]]]])
torch.Size([1, 1, 4, 4])


In [24]:
output = conv2d(input_feat)
output

/Users/barrywu/anaconda3/envs/AI/lib/python3.8/site-packages/torch/nn/modules/conv.py:459: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1682343685278/work/aten/src/ATen/native/Convolution.cpp:1004.)
  return F.conv2d(input, weight, bias, self.stride,


tensor([[[[16., 11., 16., 15.],
          [25., 20., 10., 13.],
          [ 9.,  9., 10., 12.],
          [ 1.,  0.,  2.,  4.]]]])